### ISSUE TITLE
Fix error message

### ISSUE THREAD

**Issue by SemenMartynov** [ohtanii/trpo_json#2]
Error message should contain uploaded file name https://github.com/SemenMartynov/SPbPU_TRPO_2017/blob/master/Task01.RUS.txt#L45

**Comment by ohtanii** [comment]
Now it's ok)
Filename is shown in "resource"
![bbw8dwl-wo0](https://user-images.githubusercontent.com/22347362/35275184-fdea590c-004f-11e8-891f-a68aacd57a98.jpg)

**Comment by SemenMartynov** [comment]
Please link your commit with the git issues via comments.

**Comment by SemenMartynov** [comment]
I don't see `errorPlace`.

**Comment by ohtanii** [comment]
errorPlace is shown with errorMessge
![bbw8dwl-wo0](https://user-images.githubusercontent.com/22347362/35276896-085e70fc-0056-11e8-88e8-8a59bf939df0.jpg)

**Comment by SemenMartynov** [comment]
Expected format:
```
{
 "errorCode"  : 12345,
 "errorMessage" : ["verbose, plain language description of the problem with hints about how to fix it]",
 "errorPlace" : ["highlight the point where error has occurred"],
 "resource"   : ["filename"],
 "request-id" : ["the request id generated by the API for easier tracking of errors"],
}
```

**Comment by ohtanii** [comment]
Fixed
![m-czzhjwaza](https://user-images.githubusercontent.com/22347362/35332105-dc1c87de-011a-11e8-9549-31d561086603.jpg)

**Comment by SemenMartynov** [comment]
OK, looks good.
