### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by SemenMartynov** [ohtanii/trpo_json#3]
Go ahead and implement the 2nd task.

**Comment by ohtanii** [comment]
Please check the implementation of task 2  in branch ohtanii-task2

**Comment by SemenMartynov** [comment]
No, all releases should be in the master branch.
We discussed it on the seminar, when we talked about git-flow.

**Comment by ohtanii** [comment]
Ok, now it's in the master branch.

**Comment by SemenMartynov** [comment]
```
$ ./gradlew createImage && docker run -d -p 80:80 jjson
-bash: ./gradlew: Permission denied

```

**Comment by ohtanii** [comment]
Try: 
`sudo ./gradlew createImage && docker run -d -p 80:80 jjson`

**Comment by ohtanii** [comment]
Before this command run: `chmod +x gradlew`

**Comment by SemenMartynov** [comment]
Nope) Just fix this issue in your repo.

**Comment by SemenMartynov** [comment]
Any updates?

**Comment by ohtanii** [comment]
Please try again, it must work now

**Comment by SemenMartynov** [comment]
Please remove `build` folder from your repo
